### ISSUE TITLE
Создать локальный сервис задач

### ISSUE THREAD

**Issue by astronik00** [SUAI-TaskPlanner-Contest/TaskPlanner#46]
### Краткое описание

Необходимо разработать класс сервиса задач, который работал бы с репозиторием задач, а также с классом для валидации данных. Организовать обработку исключений.

### Функциональные требования или документация

[Класс задачи]() 
[Класс репозитория задач]()
[Валидатор задач]()

### Обобщенное решение

- [ ] Ознакомиться с указанными файлами
- [ ] Создать класс сервиса

### Выходной результат

Класс .py

**Comment by aleksandra-shchegoleva** [comment]
@astronik00 Посмотри, пожалуйста, корректно ли я сделала update своей ветки до main. Исходно ветка сильно отставала.
