### ISSUE TITLE
Создать ui Главного окна

### ISSUE THREAD

**Issue by slavakyrlan** [SUAI-TaskPlanner-Contest/TaskPlanner#67]
### Краткое описание

Необходимо создать QML "Главное окно"

### Функциональные требования или иные документы

[Дизайн](https://www.figma.com/file/92KUEQOpS91HsI76KbFSFb/main?type=design&node-id=0-1)

### Обобщенное решение

- [x] Сверстать общий вид главного окна
- [x] Сверстать окно (о пользователе, кнопки: настройки, диаграмма Ганта)
- [x] Сверстать кнопки добавления задач
- [x] Сверстать кнопку настроек у задач
- [x] Сверстать окна для редактирования/добавления подзадачи

### Выходной результат

Файл главного окна QML и необходимые ресурсы.

**Comment by slavakyrlan** [comment]
@astronik00 записал еще раз [видео](https://youtu.be/RREMiOd7EFg).
Напиши, пожалуйста, что еще поменять. Или можно отправлять это на "pull request"?

**Comment by astronik00** [comment]
> @astronik00 записал еще раз [видео](https://youtu.be/RREMiOd7EFg).
> Напиши, пожалуйста, что еще поменять. Или можно отправлять это на "pull request"?
> 
> 
> Выглядит супер, но поиск родителя надо убрать и сделать просто лейбл + readonly поле. Кликаешь и нужно передать родителя сразу у задачи, на которой кликнули добавление (не считая корневой, где плюсик сверху).
> Тогда же в задаче, которая добавляется через глобальный клик (на панели с заголовком, комбобоксом и кнопкой пуша) необходимо либо выпилить в принципе кнопку, либо автоматом заполнить рид онли полем с надписью "Нет", к примеру

ой, я твое отредачила XD

**Comment by astronik00** [comment]
В дополнении к этому - ознакомиться с тем, что я скинула в тг беседу и сделать заготовки вызова питоновских функций по сигналу. Сами функции питона оставить пустыми, главное их написать и связать

**Comment by astronik00** [comment]
Странно, почему у тебя вид с слайдером выводится на редактирование. Слайдер должен быть только на окне, предназначенном для мерджа.

**Comment by astronik00** [comment]
Ну и также кстати надо обсудить, что делать с мерджем, раз не получается свитч с 3 состояниями. Я вот сейчас ищу какой-то пример, но вообще ничего нет

**Comment by astronik00** [comment]
@slavakyrlan 

https://stackoverflow.com/questions/10228783/qml-how-to-create-a-3-state-custom-button-made-from-images

может, тут что-то хоть немного применимое?

**Comment by slavakyrlan** [comment]
![Image](https://github.com/SUAI-TaskPlanner-Contest/TaskPlanner/assets/127335939/a5dc4a5e-cc4d-4543-bd5e-1927a3143386)

- [ ] кнопка закрыть приложение
+ то что указано выше

**Comment by slavakyrlan** [comment]
[Видео](https://youtu.be/SPbT01xLehY) с окном

Поработать:
- [ ] над стилями текста, цвет серых объектов
- [ ] функции, классы в py
