### ISSUE TITLE
Изменить окно авторизации

### ISSUE THREAD

**Issue by pavelparfishov** [SUAI-TaskPlanner-Contest/TaskPlanner#75]
## Design

[//]: # (Название лейбла: UI)

### Краткое описание

[//]: # (Короткое описание форм, которых нужно спроектировать)

Описание задачи

### Функциональные требования или иные документы
Окно, которое необходимо изменить:

![Image](https://user-images.githubusercontent.com/78814540/239311210-16407f00-ad55-48e6-b5cf-146811a2643b.png)

[//]: # (Список документов, или требований, которым созданные прототипы интерфейса должны удовлетворятиь)

### Обобщенное решение

- [ ] Изучить требования
- [ ] Представить как все должно выглядеть
- [ ] Внести изменения в существующее окно авторизации

### Выходной результат
Измененное окно авторизации

**Comment by astronik00** [comment]
@pavelparfishov 

Необходимо добавить еще одно текстовое поле для ввода "ссылка на сервер". Не очень красиво будет, но ничего не поделаешь(
Также сделай заготовку для сигналов в соответствие с тем, что я кидала в тг. Нужны самое главное функции питона, их можно оставить пустыми.

**Comment by pavelparfishov** [comment]
@astronik00 Обновил окно.

![Image](https://github.com/SUAI-TaskPlanner-Contest/TaskPlanner/assets/78814540/2d459d30-37fd-4658-b192-f444402d3d12)



![Image](https://github.com/SUAI-TaskPlanner-Contest/TaskPlanner/assets/78814540/f9c2c083-5344-464b-a9bf-f2c6af1019a5)

**Comment by astronik00** [comment]
@pavelparfishov 
Внешний вид полностью устраивает
